import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "../../lib/authProvider";
import { motion, AnimatePresence } from "framer-motion"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Sport Events App",
  description: "Generated by Bitsmith1",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <AuthProvider>{children}</AuthProvider>
        </main>
      </body>
    </html>
  );
}
